# https://cloud.google.com/sql/docs/mysql/connect-build
steps:
  # ----------------- Decrypting JSON ENV file -----------------
  - id: 'decrypt-swarmstar-secrets'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=$_ENV_SECRET_NAME > /workspace/swarmstar-secrets.json

  # ----------------- Build App Docker Image -----------------
  # Need to build app at root directory due to schema.gql being in ./server
  # This step creates the .env file for the production react app build
  - id: 'create-swarmstar-secrets-file'
    name: 'gcr.io/cloud-builders/docker'
    dir: './client'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y jq
        echo VITE_CLERK_PUBLISHABLE_KEY=\"$(jq -r '."VITE_CLERK_PUBLISHABLE_KEY"' /workspace/swarmstar-secrets.json)\">> .env
        cat .env

  - id: 'build-client-docker-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/client-image:$COMMIT_SHA', '-f', './client/Dockerfile', '.']

  - id: 'push-client-docker-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/client-image:$COMMIT_SHA']

  # ----------------- Deploying App Docker Image to Cloud Run Service -----------------
  - id: 'deploy-client-docker-image'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_CLOUD_RUN_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/client-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1'

images: ['gcr.io/$PROJECT_ID/client-image:$COMMIT_SHA']

substitutions:
  _ENV_SECRET_NAME: swarmstar-secrets
  _CLOUD_RUN_SERVICE_NAME: client

options:
  logging: CLOUD_LOGGING_ONLY
