#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     ENUM SECTION STARTS                   |
# |                                                           |
# \___________________________________________________________/

enum ActionEnum {
  FOLDER
  PLAN
  ROUTE_ACTION
  CODE
  SEARCH
  REVIEW_GOAL_PROGRESS
}

enum MessageRoleEnum {
  USER
  SYSTEM
  ASSISTANT
}

enum AgentEdgeTypeEnum {
  SPAWN
  KILL
  RETURN
}

enum ChatStatusEnum {
  ACTIVE
  COMPLETED
}

enum PanelContentEnum {
  INFORMATION_GRAPH
  ACTION_GRAPH
  AGENT_GRAPH
  TOOL_GRAPH
  CHAT
  EMPTY
}

enum SplitDirectionEnum {
  HORIZONTAL
  VERTICAL
}

enum ThemeEnum {
  SNOW
  MIDNIGHT
  NEUTRAL
  ICE
  VOLCANO
  GREEN
  ELIXIR
  FOREST
  RED
  BLUE
  PURPLE
  CONCRETE
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     ENUM SECTION ENDS                     |
# |                                                           |
# \___________________________________________________________/

# ___________________________________________________________

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     TYPE SECTION STARTS                   |
# |                                                           |
# \___________________________________________________________/


type User {
  id: ID!
  swarms: [Swarm!]
  informationGraphs: [InformationGraph!]
  panelLayouts: [PanelLayout!]
  theme: ThemeEnum
}

type PanelLayout {
  id: ID!
  isEditable: Boolean
  title: String
  panelNodes: [PanelNode!]
}

type PanelNode {
  id: ID!
  content: PanelContentEnum!
  split: SplitDirectionEnum
  firstChild: PanelNode
  secondChild: PanelNode
  parentId: ID
}

type Settings {
  id: ID!
  theme: String
}

type Swarm {
  id: ID!
  title: String
  goal: String
  chats: [Chat!]
  agentGraph: AgentGraph
  informationGraph: InformationGraph
}

"""
Information Graph
"""
type InformationGraph {
  id: ID!
  title: String
  nodes: [InformationNode!]
  edges: [informationEdge!]
}

type InformationNode {
  id: ID!
  title: String
  type: String
}

type informationEdge {
  id: ID!
  startNodeId: ID!
  endNodeId: ID!
}

"""
Agent Graph
"""
type AgentGraph {
  id: ID!
  nodes: [AgentNode!]
  edges: [AgentEdge!]
}

type AgentNode {
  id: ID!
  title: String
  type: String
}

type AgentEdge {
  id: ID!
  type: AgentEdgeTypeEnum
  startNodeId: ID!
  endNodeId: ID!
}

"""
Action Graph
"""
type ActionGraph {
  id: ID!
  nodes: [ActionNode!]
  edges: [ActionEdge!]
}

type ActionNode {
  id: ID!
  title: String
  description: String
  type: String
}

type ActionEdge {
  id: ID!
  startNodeId: ID!
  endNodeId: ID!
}

"""
Tool Graph
"""
type ToolGraph {
  id: ID!
  nodes: [ToolNode!]
  edges: [ToolEdge!]
}

type ToolNode {
  id: ID!
  title: String
  type: String
}

type ToolEdge {
  id: ID!
  startNodeId: ID!
  endNodeId: ID!
}


"""
Chat
"""
type Chat {
  id: ID!
  title: String
  messages: [Message!]
  status: ChatStatusEnum
}

type Message {
  id: ID!
  content: String
  role: MessageRoleEnum
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     TYPE SECTION ENDS                     |
# |                                                           |
# \___________________________________________________________/

# ___________________________________________________________

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                   QUERY SECTION STARTS                    |
# |                                                           |
# \___________________________________________________________/

type RootQuery {
  user: User
  actionGraph: ActionGraph
  toolGraph: ToolGraph
  swarm(swarmId: ID!): Swarm
  chat(chatId: ID!): Chat
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     QUERY SECTION ENDS                    |
# |                                                           |
# \___________________________________________________________/

# ___________________________________________________________

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                   MUTATION SECTION STARTS                 |
# |                                                           |
# \___________________________________________________________/

type RootMutation {
  swarmMutation: SwarmMutation
  informationGraphMutation: InformationGraphMutation
  chatMutation: ChatMutation
  userMutation: UserMutation
}

input CreateSwarmRequest {
  title: String!
  goal: String!
  informationGraphId: ID!
}

type SwarmMutation {
  createSwarm(input: CreateSwarmRequest!): User
}

input CreateInformationGraphRequest {
  title: String!
}

type InformationGraphMutation {
  createInformationGraph(input: CreateInformationGraphRequest!): User
}

input SendMessageRequest {
  content: String!
  chatId: ID!
}

type ChatMutation {
  sendMessage(input: SendMessageRequest!): Chat
}

input PanelLayoutCreateInput {
  title: String
  panelNodes: [PanelNodeCreateInput!]
}

input PanelNodeCreateInput {
  id: ID
  content: PanelContentEnum
  split: SplitDirectionEnum
  parentId: ID
  firstChild: PanelNodeCreateInput
  secondChild: PanelNodeCreateInput
}

type UserMutation {
  createPanelLayout(input: PanelLayoutCreateInput!): User
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                   MUTATION SECTION ENDS                   |
# |                                                           |
# \___________________________________________________________/

# ___________________________________________________________

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                   SUBSCRIPTION SECTION STARTS             |
# |                                                           |
# \___________________________________________________________/

type Subscription {
  messageSent(chatId: ID!): Message
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                   SUBSCRIPTION SECTION ENDS               |
# |                                                           |
# \___________________________________________________________/

schema {
  query: RootQuery
  mutation: RootMutation
  subscription: Subscription
}
