#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     TYPE SECTION STARTS                   |
# |                                                           |
# \___________________________________________________________/


enum UserTypeEnum {
  USER
  ADMIN
}

enum ActionEnum {
  FOLDER
  PLAN
  ROUTE_ACTION
  CODE
  SEARCH
  REVIEW_GOAL_PROGRESS
}

enum MessageRoleEnum {
  USER
  SYSTEM
  ASSISTANT
  SWARMSTAR
}

type User {
  id: ID!
  type: UserTypeEnum
  swarms: [Swarm!]
  memories: [Memory!]
}

type Swarm {
  id: ID!
  title: String
  goal: String
  data: SwarmData
}

type SwarmData {
  id: ID!
  chats: [Chat!]
  actionNodes: [ActionNode!]
  memoryNodes: [MemoryNode!]
  actionMetadataNodes: [ActionMetadataNode!]
}

type Memory {
  id: ID!
  title: String
  memoryNodes: [MemoryNode!]
}

type Chat {
  id: ID!
  title: String
  messages: [Message!]
}

type ActionNode {
  id: ID!
  title: String
  parentId: ID
}

type MemoryNode {
  id: ID!
  title: String
  parentId: ID
}

type ActionMetadataNode {
  id: ID!
  title: String
  parentId: ID
  description: String
}

type Message {
  id: ID!
  content: String
  role: MessageRoleEnum
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     TYPE SECTION ENDS                     |
# |                                                           |
# \___________________________________________________________/

# ___________________________________________________________

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                   QUERY SECTION STARTS                    |
# |                                                           |
# \___________________________________________________________/

input CreateMemoryRequest {
  title: String!
}

input CreateSwarmRequest {
  title: String!
  goal: String!
  memoryId: ID!
}

type SwarmMutation {
  createSwarm(input: CreateSwarmRequest!): User
}

type MemoryMutation {
  createMemory(input: CreateMemoryRequest!): User
}

type ActionMetadataQuery {
  getActionMetadata: [ActionMetadataNode]
}

#  ___________________________________________________________
# /                                                           \
# |                                                           |
# |                     QUERY SECTION ENDS                    |
# |                                                           |
# \___________________________________________________________/

type RootMutation {
  swarmMutation: SwarmMutation
  memoryMutation: MemoryMutation
}

type RootQuery {
  fetchSwarm(id: ID!): Swarm
  fetchMemory(id: ID!): Memory
  fetchUser: User
  actionMetadata: ActionMetadataQuery
}

schema {
  query: RootQuery
  mutation: RootMutation
}
