FROM node:18

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN yarn install

# Copy the rest of the application code
COPY . .
RUN yarn build

CMD ["node", "dist/websocket-server.js"]