fragment User on User {
  id
  type
  swarms {
    ...Swarm
  }
  memories {
    ...Memory
  }
}

fragment Swarm on Swarm {
  id
  title
}

fragment Memory on Memory {
  id
  title
}

fragment Chat on Chat {
  id
  title
}

fragment ActionNode on ActionNode {
  id
  title
  parentId
}

fragment MemoryNode on MemoryNode {
  id
  title
  parentId
}

fragment ActionMetadataNode on ActionMetadataNode {
  id
  title
  parentId
  description
}
