fragment User on User {
  id
  swarms {
    ...SwarmPreview
  }
  informationGraphs {
    ...InformationGraphPreview
  }
}

fragment SwarmPreview on Swarm {
  id
  title
  goal
}

fragment Swarm on Swarm {
  ...SwarmPreview
  chats {
    ...ChatPreview
  }
  agentGraph {
    ...AgentGraph
  }
  informationGraph {
    ...InformationGraph
  }
}

fragment InformationGraphPreview on InformationGraph {
  id
  title
}

fragment InformationGraph on InformationGraph {
  ...InformationGraphPreview
  nodes {
    ...InformationNode
  }
  edges {
    ...informationEdge
  }
}

fragment InformationNode on InformationNode {
  id
  title
  type
}

fragment informationEdge on informationEdge {
  id
  startNodeId
  endNodeId
}

fragment AgentGraph on AgentGraph {
  id
  nodes {
    ...AgentNode
  }
  edges {
    ...AgentEdge
  }
}

fragment AgentNode on AgentNode {
  id
  title
  type
}

fragment AgentEdge on AgentEdge {
  id
  type
  startNodeId
  endNodeId
}

fragment ChatPreview on Chat {
  id
  title
  status
}

fragment Chat on Chat {
  ...ChatPreview
  messages {
    ...Message
  }
}

fragment Message on Message {
  id
  content
  role
}

fragment ActionNode on ActionNode {
  id
  title
  type
  description
}

fragment ToolGraph on ToolGraph {
  id
  nodes {
    ...ToolNode
  }
  edges {
    ...ToolEdge
  }
}

fragment ToolNode on ToolNode {
  id
  title
  type
}

fragment ToolEdge on ToolEdge {
  id
  startNodeId
  endNodeId
}

fragment ActionGraph on ActionGraph {
  id
  nodes {
    ...ActionNode
  }
  edges {
    ...ActionEdge
  }
}

fragment ActionEdge on ActionEdge {
  id
  startNodeId
  endNodeId
}
