mutation CreateSwarm($input: CreateSwarmRequest!) {
  swarmMutation {
    createSwarm(input: $input) {
      ...User
    }
  }
}

mutation CreateInformationGraph($input: CreateInformationGraphRequest!) {
  informationGraphMutation {
    createInformationGraph(input: $input) {
      ...User
    }
  }
}

mutation SendMessage($input: SendMessageRequest!) {
  chatMutation {
    sendMessage(input: $input) {
      ...Chat
    }
  }
}

mutation CreatePanelLayout($input: PanelLayoutCreateInput!) {
  userMutation {
    createPanelLayout(input: $input) {
      ...User
    }
  }
}

mutation SelectPanelLayout($panelLayoutId: ID!) {
  userMutation {
    selectPanelLayout(panelLayoutId: $panelLayoutId) {
      ...User
    }
  }
}

mutation SelectTheme($theme: ThemeEnum!) {
  userMutation {
    selectTheme(theme: $theme) {
      ...User
    }
  }
}
