query FetchUser {
  fetchUser {
    ...User
  }
}

query FetchSwarm($swarmId: ID!) {
  fetchSwarm(swarmId: $swarmId) {
    ...SwarmWithData
  }
}

query FetchChat($chatId: ID!) {
  fetchChat(chatId: $chatId) {
    ...ChatWithData
  }
}

mutation CreateSwarm($input: CreateSwarmRequest!) {
  swarmMutation {
    createSwarm(input: $input) {
      ...User
    }
  }
}

mutation CreateMemory($input: CreateMemoryRequest!) {
  memoryMutation {
    createMemory(input: $input) {
      ...User
    }
  }
}

mutation SendMessage($input: SendMessageRequest!) {
  chatMutation {
    sendMessage(input: $input) {
      ...ChatWithData
    }
  }
}
