query FetchUser {
  user {
    ...User
  }
}

query FetchSwarm($swarmId: ID!) {
  swarm(swarmId: $swarmId) {
    ...Swarm
  }
}

query FetchChat($chatId: ID!) {
  chat(chatId: $chatId) {
    ...Chat
  }
}

query FetchActionGraph {
  actionGraph {
    ...ActionGraph
  }
}
