query FetchUser {
  user {
    ...UserFragment
  }
}

query FetchSwarm($id: ID!) {
  swarm(id: $id) {
    ...SwarmFragment
  }
}

mutation CreateSwarm($input: CreateSwarmRequest!) {
  swarmMutation {
    createSwarm(input: $input) {
      ...SwarmFragment
    }
  }
}

mutation CreateMemory($input: CreateMemoryRequest!) {
  memoryMutation {
    createMemory(input: $input) {
      ...MemoryFragment
    }
  }
}

query FetchActionMetadata {
  actionMetadata {
    getActionMetadata {
      ...ActionMetadataNodeFragment
    }
  }
}
